### ISSUE TITLE
Search in Directory searches in wrong root folder

### ISSUE THREAD

**Issue by izuzak** [atom/find-and-replace#355]
_From @1j01 on February 26, 2015 3:59_

1. Open a project folder
2. Open another folder
3. Right click the second folder and say Search in Directory

**Expected**: Results show up from files in the folder you selected
**Actual**: Results show up from files in the original folder

_Copied from original issue: atom/tree-view#384_

**Comment by izuzak** [comment]
I can reproduce this. When you select Search in Directory on a root folder, all root folders are search (as far as I can tell) 

cc @maxbrunsfeld

**Comment by 1j01** [comment]
To be clear, I'm not getting any results from any folders other than the one "main" root folder.
This whole package is built on the fact that there was a single project directory. The terminalogy is all "Project Find" ("Project Find Results", "Replace in project", `project-find:`, ...)
If you right click a subdirectory of a root folder that isn't considered the project root, it will fill the relative path to that directory from it's parent root folder but then search using that relative path relative to the "project directory"

**Comment by maxbrunsfeld** [comment]
@1j01 the problem you're describing is already fixed in the latest Atom version. However, @izuzak is right: the `Search in Directory` context-menu item causes *all* of the root folders to be searched, if they contain the same relative path. Fixing now.

**Comment by EvNaverniouk** [comment]
This is still an issue for me in Atom 1.13.0-beta8.

In what version was this supposedly fixed?

**Comment by maxbrunsfeld** [comment]
@EvNaverniouk Could you describe step by step what you're seeing, maybe include some screenshots?

**Comment by EvNaverniouk** [comment]
I have two Project Folders loaded in Atom's file tree.

The absolute directory structure for Project A looks like this:

- **ProjectA:** /Users/myname/ProjectA/
  - /index.html

The absolute directory structure for Project B looks like this:

- **ProjectB:** /Users/myname/ProjectB/
  - index.html
  - /ProjectA/
    - /index.html

In Atom's file tree, I click on the `/Users/myname/ProjectA` directory (the root of the "Project A" Project Folder) and choose "Search In Directory". I then search for a text string.

**BUG:** Atom returns me results from:
1) `/Users/myname/ProjectA/index.html`, and from
2) `/Users/myname/ProjectB/ProjectA/index.html`

I expect only result 1 to be returned since I asked to search just in that project. However, I guess, since Project B also has the same directory naming, Atom tries to search in it too?

**Comment by maxbrunsfeld** [comment]
Ah yeah, that is the expected behavior currently; I realize that the behavior can be annoying in that situation.

We wanted to avoid having a special UI control just for selecting which project folders to search, so we decided to make the `File/directory pattern` field control which root project folder was searched in addition to filtering subfolders. So if you type a folder name in that field, we search any project folders with that name, *and* any subfolders with that name.

**Comment by maxbrunsfeld** [comment]
If you have ideas for making the behavior more clear without significantly complicating the UI, I'm definitely open to them.

**Comment by EvNaverniouk** [comment]
Is there a reason why you can't pass the absolute path to the `file/directory pattern`? Right now choosing "Search In Directory" generates this:

![screen shot 2016-12-15 at 10 14 41 am 1](https://cloud.githubusercontent.com/assets/226640/21236321/6e65a68a-c2af-11e6-9713-31168dbcde98.png)

Whereas, I would expect it to generate:

![screen shot 2016-12-15 at 10 15 05 am](https://cloud.githubusercontent.com/assets/226640/21236323/7471042a-c2af-11e6-9021-1acbc4e0c79a.png)

I guess the other issue is that in that second screenshot, having an absolute path as the search dir doesn't work at all.

**Comment by maxbrunsfeld** [comment]
Ah yeah, that's a bug; the absolute path should work.
