### ISSUE TITLE
'whole word' search fails when the string starts with $ (dollar sign)

### ISSUE THREAD

**Issue by a7madgamal** [atom/find-and-replace#576]
Atom 1.0.19 on Mac

$example = x;
when I search for $example and turn on 'whole word' I get 0 results and when I turn it off works normally.

As a node developer and Atom lover, I took a quick look (ok not very quick :D) and found the exact problem. for some reason, regex.exec fail to work when \b\$ are next to each other.
this is from the next function inside text-buffer/lib/match-iterator.js

```javascript
    Forwards.prototype.next = function() {
      var match, matchEndIndex, matchLength, matchStartIndex, submatch;
      if (match = this.regex.exec(this.text)) {
```

**Comment by 50Wliu** [comment]
I'm going to assume that this was fixed by #583.

**Comment by benogle** [comment]
This is still an issue because `$` is not a word char.

**Comment by PhiLhoSoft** [comment]
I confirm it is still an issue even after I declared $ as a word character (for JS, Java, PHP, etc.) via the nonWordCharacters setting:

".source.stylus":
  editor:
    nonWordCharacters: "/\\()\"':,;<>~!%^&*|+=[]{}`?…"

for example.
I also removed - (and #, etc.) from non word chars, and Find in Whole word mode ignores it too. This module should take in account this setting.
Thanks.

**Comment by a7madgamal** [comment]
I don't think this this should be connected or related to _nonWordCharacters_ or any other other settings
this should work out of the box regardless of language or grammer
I'm saying this to point that even if it's fixed with _nonWordCharacters_ it shouldn't be considered closed i think

**Comment by PhiLhoSoft** [comment]
@a7madgamal Why? The concept of word IS dependent on language. In CSS, foo-bar is a "word" (identifier), and it is not in JS. $ is allowed in identifier names in some languages, not in others. Etc.
Even in English / Markdown (for example), in-line or e-mail are words.
Beside, it will work "out of the box" as there is a default value for this setting.

**Comment by a7madgamal** [comment]
@PhiLhoSoft mmm never thought of it like that
I still think it's better to blindly replace without considering any rules, search shouldn't assume that I'm looking for identifier or any other type, just text

if I replace $test in the whole project I don't want to think about every file grammer, I just want to see ALL the results where this TEXT is found and followed only by a white character, end of line or a new line.

processing this will probably make the search slower, introduce more issues in the future for current and old grammers

the find and find in project is crucial to all developers, failing to detect some or all results for find and replace can be disastrous and very hard to fix specially if the tool I probably use fails me. I was really annoyed when i found this issue by luck seeing the exact string I'm looking for in front of me but not detected by atom, you don't want that :D

**Comment by PhiLhoSoft** [comment]
@a7madgamal I am not sure what you are talking about.
Here, the discussion is about the "Whole word" option of the search. Which is generally used to find identifiers: we want to find the fooBar variable, not the fooBarWithSuffix one.
If you don't want the feature, just deactivate it.

It can be done with regular expressions, but that's more typing, and potentially escaping.

**Comment by a7madgamal** [comment]
@PhiLhoSoft I don't think "whole word" is tied to variables only.
I'm not an expert so whatever the maintainers think is fine by me, maybe I was using it wrong my whole life!

**Comment by menocomp** [comment]
The issue is still there. However, I found a different workaround by using regular expression search. So if you are searching for $example write it in the search box as [$]example and tick regex search box and then hit search.

**Comment by mikebronner** [comment]
I would agree that this is still an issue. For the purposes of searching, any consecutive set characters should be considered a word, determined only be surrounding whitespace.

**Comment by Daijobou** [comment]
I want report this issue too. Thats very frustrating for PHP/JavaScript developers.

@menocomp Thanks for this tip, unfortunately its not working for me (atom 1.24.0). :(

**Comment by tkulis** [comment]
I also wanted to report this issue. It is frustrating. It is just search function guys, why you need so much time ;).
